version: '3'
services:
    simpleapi:
        container_name: simpleapi
        image: dreamnelson/simpleapi:mysql
        ports:
            - '8080-8090:8080'
        deploy:
            replicas: 2
